name: update bot
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    env:
      MAVEN_OPTS: --enable-preview
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up repository
        run: |
          cd ~/nowbot
          git fetch --all
          git reset --hard origin/master
          git pull
          git lfs pull
      - name: Build project
        run: |
          cd ~/nowbot
          mvnd clean
          mvnd package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nowbot-linux
          path: ~/nowbot/target/nowbot-linux.jar
  update:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Update
        run: |
          cd ~/nowbot
          mv ~/nowbot/target/nowbot-linux.jar ~/work
          sudo systemctl stop nowbot
          sleep 5
          sudo systemctl start nowbot
